name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build lambdas
      run:  |
            cd infrastructure/lib/lambdas
            yarn add @types/node --save-dev
            yarn install
            yarn build

    - name: Deploy backend
      run:  |
            cd infrastructure/
            yarn install
            yarn cdk deploy --require-approval never